configVersion: 1.0.0

DefaultValues:
  - defaultLanguage:English
  - defaultItallic:true
  - defaultBold:false
  - defaultUnderlined:false
  
PlayerData:
  UltraFireFX:
    - language:English
    - itallic:true
    - bold:false
    - underlined:false
  Notch:
    - language:Swedish
    - itallic:true
    - bold:true
    - underlined:false
  CaptJackParrot:
    - language:Pirate
    - itallic:false
    - bold:false
    - underlined:false
