name: MCTranslate
main: me.ultrafirefx.MCTranslate.Main
version: 1.0.0
author: UltraFireFX

commands:
  command1:
    description: Does stuff!
    aliases: cmd1
    permission: plugin.command1
    usage: Syntax error! /plugin command arg1 arg2!

permissions:
  mctranslate.*
    description: Blah
    default: false
    children:
      plugin.permission1: true
      plugin.permission2: true
      plugin.permission3: true
  mctranslate.permission1: true
    description: Blah, blah
    default: true
  mctranslate.permission2: true
    decription: Blah, blah, blah
    default: false
  mctranslate.permission3: true
    description: Blah, blah, blah, blah
    default: false
